[workspace]
preview = ["pixi-build"]
channels = ["nvidia/label/cuda-12.1.0", "conda-forge"]
platforms = ["linux-64"]

[package]
name = "InstantMesh"
description = "Creates 3D meshes from images"
version = "1.0.0"

[build-system]
build-backend = { name = "pixi-build-python", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[host-dependencies]
python = ">=3.10,<3.11"
gxx = {version = "11.1.0"}

[system-requirements]
cuda = "12"

[dependencies]
ffmpeg = "*"
ninja = "*"
pytorch-gpu = ">=2.1.0"
torchvision = "*"
xformers = "0.0.23.post1"
pytorch-lightning = "2.1.2"
transformers = "*"
diffusers = "0.21.4"
onnxruntime = "*"
rembg = "*"
triton = "*"
einops = "*"
trimesh = "*"
omegaconf = "*"
torchmetrics = "*"
pymcubes = "*"
bitsandbytes = "*"
plyfile = "*"
accelerate = "0.31.0"
huggingface_hub = "0.20.2"
webdataset = "*"
imageio-ffmpeg = "*"
pyparsing = "*"
cuda = {version = "*", channel="nvidia/label/cuda-12.1.0"}
cuda-cupti = {version = "*", channel="nvidia/label/cuda-12.1.0"}

[pypi-dependencies]
instantmesh = { path = ".", editable = false }